//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hymalia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hymalia.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã bị khóa..
        /// </summary>
        internal static string _0__has_been_blocked {
            get {
                return ResourceManager.GetString("{0} has been blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được sử dụng..
        /// </summary>
        internal static string _0__has_been_used {
            get {
                return ResourceManager.GetString("{0} has been used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại hoặc đã bị xóa..
        /// </summary>
        internal static string _0__is_not_exist_or_deleted {
            get {
                return ResourceManager.GetString("{0} is not exist or deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} là dữ liệu bắt buộc..
        /// </summary>
        internal static string _0__is_required {
            get {
                return ResourceManager.GetString("{0} is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải trong khoảng từ {1} đến {2}..
        /// </summary>
        internal static string _0__must_be_between__1__and__2_ {
            get {
                return ResourceManager.GetString("{0} must be between {1} and {2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn hoặc bằng {1}..
        /// </summary>
        internal static string _0__must_be_greater_than_or_equal_to__1_ {
            get {
                return ResourceManager.GetString("{0} must be greater than or equal to {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nhỏ hơn hoặc bằng {1}..
        /// </summary>
        internal static string _0__must_be_less_than_or_equal_to__1_ {
            get {
                return ResourceManager.GetString("{0} must be less than or equal to {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có độ dài tối đa là {1}..
        /// </summary>
        internal static string _0__with_a_maximum_length_of__1_ {
            get {
                return ResourceManager.GetString("{0} with a maximum length of {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có độ dài tối thiểu là {1}..
        /// </summary>
        internal static string _0__with_a_minimum_length_of__1_ {
            get {
                return ResourceManager.GetString("{0} with a minimum length of {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn chế quyền truy cập..
        /// </summary>
        internal static string Access_denied {
            get {
                return ResourceManager.GetString("Access denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên chưa cấu hình trạng thái cho dịch vụ này..
        /// </summary>
        internal static string Admin_has_not_configured_status_for_this_service {
            get {
                return ResourceManager.GetString("Admin has not configured status for this service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên chưa cấu hình văn bản này..
        /// </summary>
        internal static string Admin_has_not_configured_this_document {
            get {
                return ResourceManager.GetString("Admin has not configured this document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên chưa cấu hình dịch vụ này..
        /// </summary>
        internal static string Admin_has_not_configured_this_service {
            get {
                return ResourceManager.GetString("Admin has not configured this service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn lưu văn bản này..
        /// </summary>
        internal static string Do_you_want_to_save_this_document {
            get {
                return ResourceManager.GetString("Do you want to save this document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn gửi hồ sơ này đến SGTVT Hải Phòng?.
        /// </summary>
        internal static string Do_you_want_to_send_this_profile {
            get {
                return ResourceManager.GetString("Do you want to send this profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn bỏ qua văn bản này?.
        /// </summary>
        internal static string Do_you_want_to_skip_this_document {
            get {
                return ResourceManager.GetString("Do you want to skip this document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình xử lý..
        /// </summary>
        internal static string Error_in_processing {
            get {
                return ResourceManager.GetString("Error in processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp tin không được hỗ trợ. Vui lòng chỉ sử dụng các định dạng sau: .
        /// </summary>
        internal static string File_is_not_support_this_format__Format_must_be__ {
            get {
                return ResourceManager.GetString("File is not support this format. Format must be: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng {0} không hợp lệ..
        /// </summary>
        internal static string Invalid__0__format {
            get {
                return ResourceManager.GetString("Invalid {0} format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        internal static string Invalid_data {
            get {
                return ResourceManager.GetString("Invalid data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng email không hợp lệ..
        /// </summary>
        internal static string Invalid_email_format {
            get {
                return ResourceManager.GetString("Invalid email format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số không hợp lệ..
        /// </summary>
        internal static string Invalid_parameters {
            get {
                return ResourceManager.GetString("Invalid parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng số di động không hợp lệ..
        /// </summary>
        internal static string Mobile_format_is_wrong {
            get {
                return ResourceManager.GetString("Mobile format is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số di động.
        /// </summary>
        internal static string Mobile_number {
            get {
                return ResourceManager.GetString("Mobile number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập văn bản trước khi tải hồ sơ này..
        /// </summary>
        internal static string Please_enter_document_before_download_this_profile {
            get {
                return ResourceManager.GetString("Please enter document before download this profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cập nhật đầy đủ các tài liệu sau:.
        /// </summary>
        internal static string Please_upload_documents {
            get {
                return ResourceManager.GetString("Please upload documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ hồ sơ thành công..
        /// </summary>
        internal static string Profile_cancelled_successful {
            get {
                return ResourceManager.GetString("Profile cancelled successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc kết thúc. Vui lòng đăng nhập lại..
        /// </summary>
        internal static string Session_ended_please_resign_in {
            get {
                return ResourceManager.GetString("Session ended please resign-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là dữ liệu bắt buộc..
        /// </summary>
        internal static string This_is_required_field {
            get {
                return ResourceManager.GetString("This is required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã gửi mã hồ sơ đến thiết bị di động của bạn. Vui lòng kiểm tra tin nhắn để nhận mã hồ sơ và thực hiện các bước tiếp theo..
        /// </summary>
        internal static string We_sent_profile_number_to_your_number__Please_check_message_box_to_continue {
            get {
                return ResourceManager.GetString("We sent profile number to your number. Please check message box to continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể hủy hồ sơ này..
        /// </summary>
        internal static string You_cannot_cancel_this_profile {
            get {
                return ResourceManager.GetString("You cannot cancel this profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể bỏ qua bước nhập này..
        /// </summary>
        internal static string You_cannot_skip_this_step {
            get {
                return ResourceManager.GetString("You cannot skip this step", resourceCulture);
            }
        }
    }
}
